### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by uniibu**
test 4

### CODE REVIEW

**Comment by uniibu** [comment]
testest

**Comment by uniibu** [comment]
test `code` **bold**  [https://github.com/uniibu/blank-repo/pull/13](PR)
- [x] **arrow** - callbacks to arrow functions
    - [x] Converts bound functions like `function(){}.bind(this)`
    - [x] not applied to unbound functions that use `this`
    - [x] not applied to functions that use `arguments`
    - [x] not applied to object properties (use `obj-method` transform)
    - [ ] does not remove `that = this` assignments
- [x] **arrow-return** - drop return statements in arrow functions
    - [x] converts immediate return `{ return x; }` to `=> x`
    - [x] applies to arrow functions and nested arrow functions
    - [ ] LIMITATION only applies to arrow functions (run the `arrow` transform first)

**Comment by uniibu** [comment]
test `code` **bold**  [https://github.com/uniibu/blank-repo/pull/13](PR)
- [x] **arrow** - callbacks to arrow functions
    - [x] Converts bound functions like `function(){}.bind(this)`
    - [x] not applied to unbound functions that use `this`
    - [x] not applied to functions that use `arguments`
    - [x] not applied to object properties (use `obj-method` transform)
    - [ ] does not remove `that = this` assignments
- [x] **arrow-return** - drop return statements in arrow functions
    - [x] converts immediate return `{ return x; }` to `=> x`
    - [x] applies to arrow functions and nested arrow functions
    - [ ] LIMITATION only applies to arrow functions (run the `arrow` transform first)

**Comment by uniibu** [comment]
test `code` **bold**  [https://github.com/uniibu/blank-repo/pull/13](PR)
- [x] **arrow** - callbacks to arrow functions
    - [x] Converts bound functions like `function(){}.bind(this)`
    - [x] not applied to unbound functions that use `this`
    - [x] not applied to functions that use `arguments`
    - [x] not applied to object properties (use `obj-method` transform)
    - [ ] does not remove `that = this` assignments
- [x] **arrow-return** - drop return statements in arrow functions
    - [x] converts immediate return `{ return x; }` to `=> x`
    - [x] applies to arrow functions and nested arrow functions
    - [ ] LIMITATION only applies to arrow functions (run the `arrow` transform first)

**Comment by uniibu** [comment]
test `code` **bold**  [PR](https://github.com/uniibu/blank-repo/pull/13) @uniibu 
- [x] **arrow** - callbacks to arrow functions
    - [x] Converts bound functions like `function(){}.bind(this)`
    - [x] not applied to unbound functions that use `this`
    - [x] not applied to functions that use `arguments`
    - [x] not applied to object properties (use `obj-method` transform)
    - [ ] does not remove `that = this` assignments
- [x] **arrow-return** - drop return statements in arrow functions
    - [x] converts immediate return `{ return x; }` to `=> x`
    - [x] applies to arrow functions and nested arrow functions
    - [ ] LIMITATION only applies to arrow functions (run the `arrow` transform first)

**Comment by bitslergithook** [comment]
> test `code` **bold** [PR](https://github.com/uniibu/blank-repo/pull/13) @uniibu
> 
> * [x]  **arrow** - callbacks to arrow functions
>   
>   * [x]  Converts bound functions like `function(){}.bind(this)`
>   * [x]  not applied to unbound functions that use `this`
>   * [x]  not applied to functions that use `arguments`
>   * [x]  not applied to object properties (use `obj-method` transform)
>   * [ ]  does not remove `that = this` assignments
> * [x]  **arrow-return** - drop return statements in arrow functions
>   
>   * [x]  converts immediate return `{ return x; }` to `=> x`
>   * [x]  applies to arrow functions and nested arrow functions
>   * [ ]  LIMITATION only applies to arrow functions (run the `arrow` transform first)

**Comment by uniibu** [comment]
https://github.com/uniibu/blank-repo/pull/13#issuecomment-458306448

**Comment by uniibu** [comment]
https://github.com/uniibu/blank-repo/pull/13#issuecomment-458347930

**Comment by uniibu** [comment]
https://github.com/uniibu/blank-repo/pull/13#issuecomment-458348439

**Comment by uniibu** [comment]
https://github.com/uniibu/blank-repo/pull/13#issuecomment-458349327

**Pull request merged**
